[#24] Undefined reference to
g++ -o main_file main_file.cpp shaderprogram.cpp map.cpp fence.cpp column.cpp cube.cpp objects.cpp lodepng.cpp -lGL -lGLEW -lglfw -lSOIL -lassimp -I.
/usr/bin/ld: /tmp/ccaZCd1N.o: in function `drawScene(GLFWwindow*)':
main_file.cpp:(.text+0x71a): undefined reference to `generateRing(ShaderProgram*)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:5: main_file] Error 1

По фиксить генерацию кольца , ошибка котрую я не вижу.
В этом коммите был изменен фрагментыный и вершинный шейдер , были
добавлини функции теней и измененая функция пердачи цветов .

Так же в main_file старый шейдер преподователя был заменен на наш .

Changes to be committed:
	modified:   fragment_shader.glsl
	modified:   main_file.cpp
	modified:   vertex_shader.glsl